app/urls.py
from django.contrib import admin
from django.urls import include, path

from app.settings import DEBUG
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace = 'main')),
    path('flight/', include('tickets.urls', namespace = 'flight')),
    path('user/', include('users.urls', namespace = 'user'))
]

if DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
        ]

tickets/urls.py
from django.urls import path

from tickets import views

app_name = 'tickets'

urlpatterns = [
    path('', views.flight, name='index'),
    path('search/', views.flight, name='search'),
    path('book/<int:flight_id>/', views.book_flight, name='book_flight'),
    path('delete_booking/<int:booking_id>/', views.delete_booking, name='delete_booking'),
    path('create/', views.create_flight, name='create_flight'), 
    path('delete/<int:flight_id>/', views.delete_flight, name='delete_flight'), 
]

tickets/models.py
from decimal import Decimal
from django.db import models

from users.models import User
        
class Airports(models.Model):
    airport_name = models.TextField(verbose_name='Название аэропорта')
    city = models.TextField(verbose_name='Город')
    iata_code = models.CharField(max_length=3, unique=True, verbose_name='IATA код')
    
    class Meta:
        db_table = 'airport'
        verbose_name = 'Аэропорт'
        verbose_name_plural = 'Аэропорты'
    
    def __str__(self):
        return f"{self.airport_name} ({self.iata_code})" 
    
class Aircrafts(models.Model):
    model = models.CharField(max_length=30, verbose_name='Модель самолета')
    
    class Meta:
        db_table = 'aircraft'
        verbose_name = 'Самолет'
        verbose_name_plural = 'Самолеты'
        
    def __str__(self):
        return self.model
    
    
class Flights(models.Model):
    departure_time = models.DateTimeField(verbose_name='Время вылета')
    arrival_time = models.DateTimeField(verbose_name='Время прибытия')
    departure_airport = models.ForeignKey(to=Airports, on_delete=models.CASCADE, 
                                          related_name = 'departure_airports',
                                          verbose_name='Аэропорт вылета')
    arrival_airport = models.ForeignKey(to=Airports, on_delete=models.CASCADE, 
                                        related_name = 'arrival_airports',
                                        verbose_name='Аэропорт прибытия')
    aircraft_code = models.ForeignKey(to=Aircrafts, on_delete=models.CASCADE, 
                                      related_name = 'aircraft_codes', 
                                      verbose_name='Код самолета')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    
    class Meta:
        db_table = 'flight'
        verbose_name = 'Рейс'
        verbose_name_plural = 'Рейсы'
        ordering = ("id",)
        
    def __str__(self):
        return f'{self.departure_airport.city} → {self.arrival_airport.city} ({self.departure_time:%Y-%m-%d %H:%M})'
    
    def get_flight_duration(self):
        if self.departure_time and self.arrival_time:
            # Вычисляем разницу между временем прибытия и временем вылета
            duration = self.arrival_time - self.departure_time

            # Преобразуем длительность в часы и минуты
            hours, remainder = divmod(duration.total_seconds(), 3600)
            minutes = remainder // 60

            return f"{int(hours)} ч {int(minutes)} мин"
        else:
            return "Нет данных"

class Tariff(models.Model):
    name = models.CharField(max_length=50, verbose_name='Название тарифа')  # Название тарифа
    
    class Meta:
        db_table = 'tariff'
        verbose_name = 'Тариф'
        verbose_name_plural = 'Тарифы'

    def __str__(self):
        return self.name
                
class Booking(models.Model):
    flight = models.ForeignKey(Flights, related_name='bookings', on_delete=models.CASCADE, verbose_name='Рейс')
    passengers = models.PositiveIntegerField(verbose_name='Пассажиры')  # Количество пассажиров
    tariff = models.ForeignKey(Tariff, on_delete=models.CASCADE, verbose_name='Класс обслуживания')  # Тариф
    total_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Полная сумма')  # Итоговая цена за бронирование
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')  # Пользователь, сделавший бронирование
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания брони')
    
    class Meta:
        db_table = 'booking'
        verbose_name = 'Бронирование'
        verbose_name_plural = 'Бронирования'

    def __str__(self):
        return f"Ticket for {self.flight} ({self.tariff}) - {self.total_price} ₽"
    

tickets/forms.py
from django import forms

from tickets.models import Flights


class FlightForm(forms.ModelForm):
    class Meta:
        model = Flights
        fields = [
            'departure_airport', 
            'arrival_airport', 
            'departure_time', 
            'arrival_time', 
            'price',
            'aircraft_code'] 

tickets/views.py
from decimal import Decimal
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.paginator import Paginator
from django.db.models import F, DecimalField, ExpressionWrapper
from django.shortcuts import get_object_or_404, redirect, render
from tickets.forms import FlightForm
from tickets.models import Flights, Booking, Tariff

def flight(request):
    page = request.GET.get('page', 1)
    order_by = request.GET.get('order_by', None)
    from_location = request.GET.get('from', None)
    to_location = request.GET.get('to', None)
    departure_date = request.GET.get('departure_date', None)
    return_date = request.GET.get('return_date', None)
    passengers = int(request.GET.get('passengers', 1) or '1')
    tariff_name = request.GET.get('tariff', None)

    flights = Flights.objects.all()

    # Применение фильтров
    if from_location:
        flights = flights.filter(departure_airport__city__icontains=from_location)
    if to_location:
        flights = flights.filter(arrival_airport__city__icontains=to_location)
    if departure_date:
        flights = flights.filter(departure_time__date=departure_date)
    
    # Применение фильтра по тарифу
    if tariff_name:
        if tariff_name == 'Комфорт':
            # Используем ExpressionWrapper для создания вычисляемого поля
            flights = flights.annotate(
                adjusted_price=ExpressionWrapper(F('price') * 1.5, output_field=DecimalField())
            )
        elif tariff_name == 'Бизнес':
            flights = flights.annotate(
                adjusted_price=ExpressionWrapper(F('price') * 2, output_field=DecimalField())
            )
        else:  # Эконом
            flights = flights.annotate(
                adjusted_price=ExpressionWrapper(F('price'), output_field=DecimalField())
            )
    else:
        # Если тариф не выбран, возвращаем исходные значения
        flights = flights.annotate(
            adjusted_price=ExpressionWrapper(F('price'), output_field=DecimalField())
        )

    # Умножение на количество пассажиров
    flights = flights.annotate(final_price=F('adjusted_price') * passengers)
    
    # Если дата обратного рейса выбрана, суммируем цену туда и обратно
    if return_date:
        flights = flights.annotate(final_price=F('final_price') + F('adjusted_price') * passengers)

    # Сохранение final_price, пассажиров и тарифа в сессии для дальнейшего использования
    if flights.exists():
        final_price = flights.first().final_price
        request.session['final_price'] = str(final_price)
        request.session['passengers'] = passengers
        request.session['tariff_name'] = tariff_name
        
    # Сортировка
    if order_by and order_by != "default":
        if order_by == "price":
            flights = flights.order_by("price")
        elif order_by == "-price":
            flights = flights.order_by("-price")
            
    paginator = Paginator(flights, 3)
    current_page = paginator.page(int(page))

    context = {
        "title": "Avia - Билеты",
        "passengers": passengers,
        "flights": current_page,
        "tariff_name": tariff_name,
    }
    return render(request, 'tickets/flight.html', context)

@login_required
def book_flight(request, flight_id):
    # Получение данных о рейсе
    flight = get_object_or_404(Flights, id=flight_id)

    passengers = int(request.session.get('passengers', 1) or '1')  # Получаем количество пассажиров
    tariff_name = request.session.get('tariff_name', 'Эконом')  # Получаем тариф
    final_price = Decimal(request.session.get('final_price', 0))  # Получаем final_price

    # Получение тарифа
    tariff = get_object_or_404(Tariff, name=tariff_name)
    
    # Создание записи бронирования
    booking = Booking.objects.create(
        flight=flight,
        passengers=passengers,
        tariff=tariff,
        total_price=final_price,
        user=request.user
    )
    booking.save()

    # Сообщение пользователю
    messages.success(request, 'Ваше бронирование успешно создано!')

    # Перенаправление на страницу с бронированиями
    return redirect('users:profile') 

def delete_booking(request, booking_id):
    # Получаем бронирование по ID
    booking = get_object_or_404(Booking, id=booking_id)
    
    # Проверяем, что пользователь является администратором или стаффом
    if request.user.is_staff or request.user.is_superuser:
        booking.delete()  # Удаляем бронирование
        messages.success(request, "Бронирование было успешно удален.")
    
    return redirect('users:profile')

def is_staff(user):
    return user.is_staff or user.is_superuser

@login_required
@user_passes_test(is_staff)
def create_flight(request):
    if request.method == 'POST':
        form = FlightForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Рейс успешно создан!')
            return redirect('tickets:index')  
    else:
        form = FlightForm()

    return render(request, 'tickets/create_flight.html', {'form': form})

# Представление для удаления рейса
@login_required
@user_passes_test(is_staff)
def delete_flight(request, flight_id):
    flight = get_object_or_404(Flights, id=flight_id)
    if request.user.is_staff or request.user.is_superuser:
        flight.delete()
        messages.success(request, "Рейс был успешно удален.")
        
    return redirect('flight:index')

tickets/templates/tickets/booking.html
{% extends "base.html" %}
{% load static %}

tickets/templates/tickets/create_flight.html
{% extends 'base.html' %}

{% block content %}
  <div class="container bg-white p-4 rounded shadow">
    <h2>Создать новый рейс</h2>

    <form method="POST">
      {% csrf_token %}
      
      <div class="mb-3">
        <label for="{{ form.departure_airport.id_for_label }}" class="form-label">Аэропорт отправления</label>
        {{ form.departure_airport }}
      </div>
      
      <div class="mb-3">
        <label for="{{ form.arrival_airport.id_for_label }}" class="form-label">Аэропорт прибытия</label>
        {{ form.arrival_airport }}
      </div>

      <div class="row">
        <div class="col-md-6 mb-3">
          <label for="departure_time" class="form-label">Дата и время вылета</label>
          <div class="input-group">
            <input type="datetime-local" name="departure_time" id="departure_time" class="form-control" value="{{ form.departure_time.value|date:'Y-m-d\TH:i' }}" />
            
          </div>
        </div>

        <div class="col-md-6 mb-3">
          <label for="arrival_time" class="form-label">Дата и время прилета</label>
          <div class="input-group">
            <input type="datetime-local" name="arrival_time" id="arrival_time" class="form-control" value="{{ form.arrival_time.value|date:'Y-m-d\TH:i' }}" />
          </div>
        </div>
      </div>

      <div class="mb-3">
        <label for="{{ form.price.id_for_label }}" class="form-label">Цена</label>
        {{ form.price }}
      </div>

      <div class="mb-3">
        <label for="{{ form.aircraft_code.id_for_label }}" class="form-label">Код самолета</label>
        {{ form.aircraft_code }}
      </div>

      <button type="submit" class="btn btn-success">Создать рейс</button>
    </form>
  </div>
{% endblock %}

tickets/templates/tickets/flight.html
{% extends 'base.html' %}
{% load static %}
{% load tickets_tags %}

{% block css %}
  <link rel="stylesheet" href="{% static 'deps/css/ticket.css' %}" />
{% endblock %}

{% block header %}
  <section class="container py-4">
    <div class="container">
      <form action="{% url "flight:search" %}" method="get" class="row g-3">
        <div class="col-md-3">
          <input type="search" class="form-control" placeholder="Откуда" name="from" required value="{{ request.GET.from }}"/>
        </div>
        <div class="col-md-3">
          <input type="search" class="form-control" placeholder="Куда" name="to" required value="{{ request.GET.to }}"/>
        </div>
        <div class="col-md-2">
          <input type="date" class="form-control" placeholder="Дата туда" name="departure_date" required value="{{ request.GET.departure_date }}"/>
        </div>
        <div class="col-md-2">
          <input type="date" class="form-control" placeholder="Дата обратно" name="return_date" value="{{ request.GET.return_date }}"/>
        </div>

        <div class="col-md-2">
          <button type="submit" class="btn btn-primary w-100">Найти билеты</button>
        </div>

        <div class="col-md-3">
          <input type="number" class="form-control" placeholder="Количество пассажиров" name="passengers" required value="{{ request.GET.passengers }}"/>
        </div>

        <!-- Выбор тарифа -->
        <div class="col-md-3">
          <input type="search" list="options" class="form-control" placeholder="Класс" name="tariff" required value="{{ request.GET.tariff }}"/>
          <datalist id="options">
            <option value="Эконом"></option>
            <option value="Комфорт"></option>
            <option value="Бизнес"></option>
          </datalist>
        </div>
      </form>
    </div>
  </section>
{% endblock %}

{% block content %}
  <div class="container" style="margin-top:150px;">
    
    <!-- Контент на странице -->
    <div class="row">
      <!-- Форма фильтров -->
      <div class="dropdown mb-2">
        <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Фильтры</button>

        <form action="{% if request.GET.from and request.GET.to and request.GET.departure_date and request.GET.tariff and request.GET.passengers or request.GET.return_date%}{% url "flight:search" %}{% else %}{% url "flight:index" %}{% endif %}" method="get" class="dropdown-menu" data-bs-theme="light">
          <!-- Передаем параметры поиска как скрытые поля -->
          <input type="hidden" name="from" value="{{ request.GET.from }}">
          <input type="hidden" name="to" value="{{ request.GET.to }}">
          <input type="hidden" name="departure_date" value="{{ request.GET.departure_date }}">
          <input type="hidden" name="return_date" value="{{ request.GET.return_date }}">
          <input type="hidden" name="tariff" value="{{ request.GET.tariff}}">
          <input type="hidden" name="passengers" value="{{ request.GET.passengers}}">

          <p class="text-black mx-3 mt-3">Сортировать:</p>
          <div class="form-check text-black mx-3">
            <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault1" value="default" 
            {% if not request.GET.order_by or request.GET.order_by == 'default' %}checked{% endif %}/>
            <label class="form-check-label" for="flexRadioDefault1">По умолчанию</label>
          </div>
          <div class="form-check text-black mx-3">
            <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault2" value="price" 
            {% if request.GET.order_by == 'price' %}checked{% endif %}/>
            <label class="form-check-label" for="flexRadioDefault2">От дешевых к дорогим</label>
          </div>
          <div class="form-check text-black mx-3">
            <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault3" value="-price" 
            {% if request.GET.order_by == '-price' %}checked{% endif %}/>
            <label class="form-check-label" for="flexRadioDefault3">От дорогих к дешевым</label>
          </div>
          <button type="submit" class="btn btn-primary mx-3 mt-3">Применить</button>
        </form>
      </div>

      <!-- Кнопки для админа и стаффа создать рейс и удалить рейс-->
      {% if request.user|is_in_group:"Сотрудники" or user.is_superuser %}
        <div class="col-12 mb-3">
          <a href="{% url 'tickets:create_flight' %}" class="btn btn-success">Создать рейс</a>
        </div>
      {% endif %}

      {% for flight in flights %}
        <!-- Карта билета -->
        <div class="container mt-5">
          <div class="ticket-card row">
            <!-- Левая колонка: информация о рейсе -->
            <div class="col-lg-8">
              <div class="d-flex justify-content-between">
                <h5>{{flight.departure_airport.city}} → {{flight.arrival_airport.city}}</h5>
                <div>
                  <div class="flight-time">{{flight.departure_time|date:"H:i"}}</div>
                  <div class="flight-info"> {{flight.departure_time|date:"d M"}}</div>
                  <div class="flight-info">{{flight.departure_airport}}</div>
                </div>
                <div>
                  <div class="flight-time">{{flight.arrival_time|date:"H:i"}}</div>
                  <div class="flight-info">{{flight.arrival_time|date:"d M"}}</div>
                  <div class="flight-info">{{flight.arrival_airport}}</div>
                </div>
                <div>
                  <div class="duration">{{ flight.get_flight_duration }}</div>
                  <div class="flight-info">Без пересадок</div>
                </div>
              </div>
              {% if request.GET.return_date %}
                <hr />
                <div class="d-flex justify-content-between">
                  <h5>{{flight.departure_airport.city}} → {{flight.arrival_airport.city}}</h5>
                  <div>
                    <div class="flight-time">{{flight.departure_time|date:"H:i"}}</div>
                    <div class="flight-info">{{flight.departure_time|date:"d M"}}</div>
                    <div class="flight-info">{{flight.departure_airport}}</div>
                  </div>
                  <div>
                    <div class="flight-time">{{flight.arrival_time|date:"H:i"}}</div>
                    <div class="flight-info">{{flight.arrival_time|date:"d M"}}</div>
                    <div class="flight-info">{{flight.departure_airport}}</div>
                  </div>
                  <div>
                    <div class="duration">{{ flight.get_flight_duration }}</div>
                    <div class="flight-info">Без пересадок</div>
                  </div>
                </div>
              {% endif %}
            </div>

            <!-- Вертикальная линия -->
            <div class="col-lg-1 d-flex align-items-center justify-content-center">
              <div class="vertical-divider"></div>
            </div>

            <!-- Правая колонка: цена и кнопка -->
            <div class="col-lg-3 ticket-price">
                  <div class="price">{{ flight.final_price|floatformat:2 }} ₽</div>
                  <div class="flight-info">За {{ request.GET.passengers }} пассажиров</div>
                  <a class="btn btn-primary" href="{% url 'tickets:book_flight' flight.id %}">Бронировать</a>
                  {% if request.user|is_in_group:"Сотрудники" or user.is_superuser %}
                    <!-- Кнопка удаления рейса -->
                    <form action="{% url 'tickets:delete_flight' flight.id %}" method="post">
                      {% csrf_token %}
                      <button type="submit" class="btn btn-danger mt-2" onclick="return confirm('Вы уверены, что хотите удалить этот рейс?')">Удалить рейс</button>
                    </form>
                  {% endif %}
            </div>
          </div>
        </div>
      {% endfor %}
    </div>

    <!-- Пагинация -->
    <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center my-4">
        <div class="custom-shadow d-flex">

          <li class="page-item {% if not flights.has_previous %}disabled{% endif %}">
            <a class="page-link" href="{% if flights.has_previous %}?{% change_params page=flights.previous_page_number %}{% else %}#{% endif %}">Предыдущая</a>
          </li>

          {% for page in flights.paginator.page_range %}
          <li class="page-item {% if flights.number == page %} active {% endif %}">
            <a class="page-link" href="?{% change_params page=page %}">{{page}}</a>
          </li>
          {% endfor %}
          
          <li class="page-item {% if not flights.has_next %}disabled{% endif %}">
            <a class="page-link" href="{% if flights.has_next %}?{% change_params page=flights.next_page_number %}{% else %}#{% endif %}">Следующая</a>
          </li>
        </div>
      </ul>
    </nav>
  </div>
{% endblock %}