app/urls.py
from django.contrib import admin
from django.urls import include, path

from app.settings import DEBUG
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace = 'main')),
    path('flight/', include('tickets.urls', namespace = 'flight')),
    path('user/', include('users.urls', namespace = 'user'))
]

if DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
        ]

tickets/urls.py
from django.urls import path

from tickets import views

app_name = 'tickets'

urlpatterns = [
    path('', views.flight, name='index'),
    path('search/', views.flight, name='search'),
    path('book/<int:flight_id>/', views.book_flight, name='book_flight'),
    path('delete_booking/<int:booking_id>/', views.delete_booking, name='delete_booking'),
    path('create/', views.create_flight, name='create_flight'), 
    path('delete/<int:flight_id>/', views.delete_flight, name='delete_flight'), 
]

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
    path('export/bookings/json/', views.export_bookings_json, name='export_bookings_json'),
    path('export/bookings/xlsx/', views.export_bookings_xlsx, name='export_bookings_xlsx'),
    path('cancel_booking/<int:booking_id>/', views.cancel_booking, name='cancel_booking'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    email = models.EmailField(verbose_name='Почта', blank=True, null=True)
    
    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователя'
        verbose_name_plural = 'Пользователи'
        
    def __str__(self):
        return self.username
        
    

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User

class UserLoginForm(AuthenticationForm):
    
    class Meta:
        model = User
        fields = ['username', 'password']
    
    username = forms.CharField()
    password = forms.CharField()
    
    # username = forms.CharField(
    #     label = 'Имя пользователя',
    #     widget=forms.TextInput(attrs={"autofocus": True,
    #                                   'class': 'form-control',
    #                                   'placeholder': 'Введите ваше имя пользователя'}))
    # password = forms.CharField(
    #     label = 'Пароль',
    #     widget=forms.PasswordInput(attrs={"autocomplete": "current-password",
    #                                       'class': 'form-control',
    #                                      'placeholder': 'Введите ваш пароль'}),
    # )
        
class UserRegistrationForm(UserCreationForm):
    
    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",
        )
        
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()
    
    
class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
        )
        
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()

users/views.py
import csv
from django.contrib.auth.decorators import login_required
from django.contrib import auth, messages
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from tickets.models import Booking
from openpyxl import Workbook

from users.forms import ProfileForm, UserLoginForm, UserRegistrationForm

def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                messages.success(request, f"{username}, Вы вошли в аккаунт")
                
                if request.POST.get('next', None):
                     return HttpResponseRedirect(request.POST.get('next'))

                return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserLoginForm()
                
    context = {
        'title': 'Avia - Авторизация',
        'form': form        
    }
    return render(request, 'users/login.html', context)

def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = form.instance
            auth.login(request, user)
            messages.success(request, f"{user.username}, Вы успешно зарегистрировались и вошли в аккаунт")
            return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserRegistrationForm()
        
    context = {
        'title': 'Avia - Регистрация',
        'form': form 
    }
    return render(request, 'users/registration.html', context)

@login_required
def profile(request):
    if request.method == 'POST':
        form = ProfileForm(data=request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, "Профиль успешно обновлен")
            return HttpResponseRedirect(reverse('user:profile'))
    else:
        form = ProfileForm(instance=request.user)
        
    # Проверка на принадлежность к группе "Сотрудники"
    if request.user.groups.filter(name="Сотрудники").exists() or request.user.is_superuser:
        # Если сотрудник или суперпользователь — показываем все бронирования
        bookings = Booking.objects.all()
    else:
        # Иначе показываем только бронирования текущего пользователя
        bookings = Booking.objects.filter(user=request.user)
    
    context = {
        'title': 'Avia - Профиль',
        'form': form,
        'bookings': bookings  # Передаем бронирования в контекст
    }
    return render(request, 'users/profile.html', context)

@login_required
def logout(request):
    messages.success(request, f"{request.user.username}, Вы вышли из аккаунта")
    auth.logout(request)
    return HttpResponseRedirect(reverse('main:index'))

def export_bookings_json(request):
    """Экспорт бронирований в формате JSON."""
    bookings = Booking.objects.all().values(
        'id', 'flight__id', 'passengers', 'tariff__name', 'total_price', 'created_at', 'user__username'
    )
    data = list(bookings)
    return JsonResponse(data, safe=False)

def export_bookings_xlsx(request):
    """Экспорт бронирований в формате XLSX."""
    bookings = Booking.objects.all().values(
        'id', 'flight__id', 'passengers', 'tariff__name', 'total_price', 'created_at', 'user__username'
    )
    
    # Создание книги Excel
    wb = Workbook()
    ws = wb.active
    ws.title = "Bookings"
    
    # Заголовки столбцов
    ws.append(['ID', 'Flight', 'Passengers', 'Tariff', 'Total Price', 'Created At', 'User'])

    # Заполнение данными
    for booking in bookings:
        created_at = booking.get('created_at')  
        # Если есть информация о временной зоне, удаляем её
        if created_at:
            # Если есть информация о временной зоне, удаляем её
            if created_at.tzinfo is not None:
                created_at = created_at.replace(tzinfo=None)
            
            # Добавляем строку в Excel с форматом даты и времени
            created_at_str = created_at.strftime('%d.%m.%Y %H:%M')
        else:
            created_at_str = "N/A"  # Если дата отсутствует, отображаем "N/A"
            
        ws.append([
            booking['id'],
            booking['flight__id'],
            booking['passengers'],
            booking['tariff__name'],
            booking['total_price'],
            created_at_str,
            booking['user__username']
        ])

    # Настроить HTTP-ответ для загрузки Excel файла
    response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    response['Content-Disposition'] = 'attachment; filename="bookings.xlsx"'

    # Сохраняем книгу в HTTP-ответ
    wb.save(response)

    return response

@login_required
def cancel_booking(request, booking_id):
    """Отменяет бронирование пользователя."""
    booking = get_object_or_404(Booking, id=booking_id, user=request.user)

    # Удаление бронирования
    booking.delete()
    messages.success(request, f"Бронирование №{booking_id} успешно отменено.")
    return redirect('users:profile')

users/templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <!-- Контент на странице -->
  <div class="row">
    <div class="container mt-5">
      <div class="row justify-content-center">
        <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded">
          <h2 class="text-center mb-4">Авторизация</h2>
          <form action="{% url "user:login" %}" method="post"> 
            {% csrf_token %}
            {% if request.GET.next %}
              <input type="hiden" name="next" value={{request.GET.next}}>
            {% endif %}
            <div class="mb-3">
              <label for="id_username" class="form-label">Имя пользователя</label>
              <input type="text" class="form-control" 
              {% if form.username.value %}{{form.username.value}}{% endif %} 
              name="username" 
              id="id_username" 
              placeholder="Введите ваше имя пользователя" required />
            </div>
            <div class="mb-3">
              <label for="id_password" class="form-label">Пароль</label>
              <input type="password" class="form-control" 
              name="password" 
              id="id_password" 
              placeholder="Введите ваш пароль" required />
            </div>

            {% comment %}
            {% for item in form %}
              <div class="mb-3">
                <label for="{{item.id_for_label}}" class="form-label">{{item.label}}</label>
                {{item}}
              </div>
            {% endfor %}
            {% endcomment %}

            <button type="submit" class="btn btn-primary btn-block">Войти</button>
          </form>
          <div class="mt-3">
            <a href="{% url "users:registration" %}">Создать аккаунт</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}
{% load tickets_tags %}

{% block content %}
  <!-- Контент на странице -->
  <div class="row">
    <div class="container mt-5">
      <div class="row">
        <!-- Профиль с данными пользователя -->
        <div class="col-md-5">
          <div class="bg-white p-4 mb-4 mx-2 rounded">
            <h3 class="text-center mb-4">Профиль пользователя</h3>
            <form action="{% url "users:profile" %}" method="post">
              {% csrf_token %}
              <div class="row">

                <div class="col-md-12 mb-3">
                  <label for="id_first_name" class="form-label">Имя*</label>
                  <input type="text" class="form-control" id="id_first_name" 
                  name="first_name"
                  placeholder="Введите ваше имя"
                  value="{{form.first_name.value}}" 
                  required />
                  {% if form.first_name.errors %}
                    <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                  {% endif %}
                </div>

                <div class="col-md-12 mb-3">
                  <label for="id_last_name" class="form-label">Фамилия*</label>
                  <input type="text" class="form-control" id="id_last_name"
                  name="last_name" 
                  placeholder="Введите вашу фамилию" 
                  value="{{form.last_name.value}}" 
                  required />
                  {% if form.last_name.errors %}
                  <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                  {% endif %}
                </div>

                <div class="col-md-12 mb-3">
                  <label for="id_username" class="form-label">Имя пользователя*</label>
                  <input type="text" class="form-control" id="id_username" 
                  name="username"
                  placeholder="Введите ваше имя пользователя" 
                  value="{{form.username.value}}" 
                  required />
                  {% if form.username.errors %}
                  <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
                  {% endif %}
                </div>

                <div class="col-md-12 mb-3">
                  <label for="id_email" class="form-label">Email*</label>
                  <input type="email" class="form-control" id="id_email" 
                  name="email"
                  placeholder="Введите ваш email *youremail@example.com" 
                  value="{{form.email.value}}" 
                  required />
                  {% if form.email.errors %}
                  <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                  {% endif %}
                </div>
              </div>

              <button type="submit" class="btn btn-primary">Сохранить</button>
            </form>
          </div>
        </div>
        <!-- Бронирования -->
        <div class="col-md-7">
          <div class="bg-white p-4 mb-4 mx-2 rounded">
            <h3 class="text-center mb-4">Бронирования</h3>
              <div class="d-flex justify-content-end mb-3">
                <a href="{% url 'users:export_bookings_json' %}" class="btn btn-secondary me-2">Выгрузить в JSON</a>
                <a href="{% url 'users:export_bookings_xlsx' %}" class="btn btn-secondary">Выгрузить в XLSX</a>
              </div>
            <div class="container" id="booking-items-container">
              {% if bookings %}
                <ul class="list-group">
                  {% for booking in bookings %}
                    <li class="list-group-item">
                      <strong>Номер бронирования:</strong> {{ booking.id }}<br>
                      <strong>Рейс:</strong> {{ booking.flight }}<br>
                      <strong>Количество пассажиров:</strong> {{ booking.passengers }}<br>
                      <strong>Тариф:</strong> {{ booking.tariff.name }}<br>
                      <strong>Цена:</strong> {{ booking.total_price }} ₽<br>
                      <strong>Дата бронирования:</strong> {{ booking.created_at|date:"d.m.Y H:i" }}
                      
                      <div class="mt-3">
                        <form action="{% url 'users:cancel_booking' booking.id %}" method="post" style="display:inline;">
                          {% csrf_token %}
                          <button type="submit" class="btn btn-warning btn-sm" onclick="return confirm('Вы уверены, что хотите отменить это бронирование?')">
                            Отменить бронирование
                          </button>
                        </form>
                      </div>

                      {% if request.user|is_in_group:"Сотрудники" or user.is_superuser %}
                        <strong>Забронировал:</strong> {{ booking.user.get_full_name }} ({{ booking.user.username }})<br>
                        
                        <!-- Кнопка удаления под информацией о бронировании -->
                        <div class="mt-3">
                          <form action="{% url 'tickets:delete_booking' booking.id %}" method="post" style="display:inline;">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Вы уверены, что хотите удалить это бронирование?')">Удалить бронирование</button>
                          </form>
                        </div>
                      {% endif %}

                    </li>
                  {% endfor %}
                </ul>
              {% else %}
                <p>У вас пока нет забронированных билетов.</p>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

users/templates/users/registration.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <!-- Контент на странице -->
  <div class="row">
    <div class="container mt-5">
      <div class="row justify-content-center">
        <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded">
          <h2 class="text-center mb-4">Регистрация</h2>
          <form action="{% url "user:registration" %}" method="post"> 
            {% csrf_token %}
            <div class="row">

              <div class="col-md-6 mb-3">
                <label for="id_first_name" class="form-label">Имя*</label>
                <input type="text" class="form-control" id="id_first_name"
                value="{% if form.first_name.value %}{{form.first_name.value}}{% endif %}"
                name="first_name" 
                placeholder="Введите ваше имя" required />
                {% if form.first_name.errors %}
                <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                {% endif %}
              </div>

              <div class="col-md-6 mb-3">
                <label for="id_last_name" class="form-label">Фамилия*</label>
                <input type="text" class="form-control" id="id_last_name" 
                value="{% if form.last_name.value %}{{form.last_name.value}}{% endif %}"
                name="last_name"
                placeholder="Введите вашу фамилию" required />
                {% if form.last_name.errors %}
                <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                {% endif %}
              </div>

              <div class="col-md-6 mb-3">
                <label for="id_username" class="form-label">Имя пользователя*</label>
                <input type="text" class="form-control" id="id_username"
                value="{% if form.username.value %}{{form.username.value}}{% endif %}" 
                name="username" 
                placeholder="Введите ваше имя пользователя" required />
                {% if form.username.errors %}
                <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
                {% endif %}
              </div>

              <div class="col-md-6 mb-3">
                <label for="id_email" class="form-label">Email*</label>
                <input type="email" class="form-control" id="id_email"
                value="{% if form.email.value %}{{form.email.value}}{% endif %}" 
                name="email" 
                placeholder="Введите ваш email" required />
                {% if form.email.errors %}
                <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                {% endif %}
              </div>

              <div class="col-md-6 mb-3">
                <label for="id_password1" class="form-label">Пароль*</label>
                <input type="password" class="form-control" id="id_password1"
                value="{% if form.password1.value %}{{form.password1.value}}{% endif %}" 
                name="password1"  
                placeholder="Введите пароль" required />
                {% if form.password1.errors %}
                <div class="alert alert-danger alert-dismissible fade show">{{form.password1.errors}}</div>
                {% endif %}
              </div>

              <div class="col-md-6 mb-3">
                <label for="id_password2" class="form-label">Подтверждение пароля*</label>
                <input type="password" class="form-control" id="id_password2"
                value="{% if form.password2.value %}{{form.password2.value}}{% endif %}" 
                name="password2"  
                placeholder="Подтвердите пароль" required />
                {% if form.password2.errors %}
                <div class="alert alert-danger alert-dismissible fade show">{{form.password2.errors}}</div>
                {% endif %}
              </div>

            </div>
            <button type="submit" class="btn btn-primary btn-block">Зарегистрироваться</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}