app/urls.py
from django.contrib import admin
from django.urls import include, path

from app.settings import DEBUG
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace = 'main')),
    path('flight/', include('tickets.urls', namespace = 'flight')),
    path('user/', include('users.urls', namespace = 'user'))
]

if DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
        ]

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    
]

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
    path('export/bookings/json/', views.export_bookings_json, name='export_bookings_json'),
    path('export/bookings/xlsx/', views.export_bookings_xlsx, name='export_bookings_xlsx'),
    path('cancel_booking/<int:booking_id>/', views.cancel_booking, name='cancel_booking'),
]

templates/base.html
{%load static%}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "deps/css/bootstrap/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "deps/css/my_css.css" %}">
    <!-- Стиль footer-a для главной страницы -->
    {% block css %}

    {% endblock css %}
    <!-- Favicons for different platforms -->
    <link rel="airplane-fresh-96" sizes="180x180" href="{% static "deps/favicon/airplane-fresh-96.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "deps/favicon/airplane-fresh-32.png" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "deps/favicon/airplane-fresh-16.png" %}">
    <link rel="manifest" href="{% static "deps/favicon/favicon-16x16.png" %}">
    <title>{{ title }}</title>
</head>

<body>
    <header class="fixed-header">
        <nav class="navbar navbar-expand-lg light-bg">
            <div class="container">               
                <a class="navbar-brand" href="{% url "main:index" %}">
                    <img src="{% static "deps/favicon/airplane-fresh-96.png" %}" alt="Airplane logo" width="30" height="30">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Левое меню -->
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link  text-black" href="{% url "flight:index" %}">Билеты</a>
                        </li>
                    </ul>
                    <!-- Правое меню -->
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        {% if not user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link  text-black" href="{% url "users:login" %}">Войти</a>
                            </li>
                        {% else %}
                            <li class="nav-item dropdown ">
                                <a class="nav-link dropdown-toggle text-black" href="#" role="button"
                                    data-bs-toggle="dropdown" aria-expanded="false">
                                    <img src="{% static "deps/favicon/profile-fresh-96.png" %}" alt="Profile Icon" width="20" height="20"> Профиль
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item  text-black" href="{% url "users:profile" %}">Личный кабинет</a>
                                    </li>
                                    {% if user.is_superuser %}
                                        <li><a class="dropdown-item  text-black" href="{% url "admin:index" %}">Админ панель</a></li>
                                    {% endif %}
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li><a class="dropdown-item  text-black" href="{% url "users:logout" %}">Выйти</a></li>
                                </ul>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        {% block header %}
        
        {% endblock header %}
    </header>
    <section class="blur">
        
        <!-- Контент -->
        <div class="container">
            <!-- Контент на странице -->
            {% include "includes/notifications.html" %}
            {% block content %}

            {% endblock content %}
        </div>
    </section>
    {% block footer %}

    {% endblock footer %}
    <script src="{% static "deps/js/jquery/jquery-3.7.0.min.js" %}"></script>
    <script src="{% static "deps/js/jquery-events.js" %}"></script>
    <script src="{% static "deps/js/jquery-count.js" %}"></script>
    <script src="{% static "deps/js/bootstrap/bootstrap.bundle.min.js" %}"></script>
    
</body>

</html>